### PR TITLE
Adding ability to watch for changes

### LINKED ISSUE #197: Add watcher to CLI

### PR DESCRIPTION
**Pull request by fidian**
This closes #197

### CODE REVIEW

**Comment by fidian** [comment]
Is there a way I can raise the priority of this pull request so that it either gets declined or I can work towards getting it approved? I've been using it daily for almost a month and it is exactly what I needed.

**Comment by src-code** [comment]
Sorry about that @fidlan, I was hoping someone else would take charge on this one, but wasn't happening.  I haven't tested your changes so I'm going to trust you've exercised this well in the last month. :)

**Comment by src-code** [comment]
Also, this needed a README update for the new option, I'll copy the help text over

**Comment by fidian** [comment]
Thanks for tackling this for me! I'll switch over my `package.json` immediately.

I appreciate that you've updated the `README` for me. Sorry for forgetting.

**Comment by redonkulus** [comment]
@fidian just wanted to let you know in atomizer@3.18.0 I enhanced the watch support to auto-watch the files passed in or configured. You can still manually add in files to watch but this makes it a little bit easier to use now.

**Pull request merged**
