### PR TITLE
fix(atomizer-plugins): run atomizer on file updates

### PR DESCRIPTION
**Pull request by redonkulus**
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

---

Fixes the atomizer-unplugin library to run atomizer on application file updates. Code copied from @maheshbansod [investigation](https://github.com/maheshbansod/atomizer-vite/blob/main/atomizerPlugin.ts).

### CODE REVIEW

**Comment by maheshbansod** [comment]
@redonkulus in my project, I'm planning to make this so that `writeFile` in `transform` will invoke during dev mode only - without the dev mode flag, transform will exit early and `buildEnd` will do the writeFile.
I think this will make build faster, since it doesn't have to update the file on every transform.

**Comment by redonkulus** [comment]
@maheshbansod how will you check dev mode without the flag, `NODE_ENV=development`?

Will you keep the `transformIndexHtml` hook as well as `buildEnd`? I think if you move it off of `transform` then the `debounce` may not be needed after all.

**Comment by redonkulus** [comment]
@maheshbansod I've added the dev flag check using `NODE_ENV` since vite already uses that standard. So now it will only call `writeFile()` in dev mode and leave writing to file in production for `buildEnd`.

**Comment by redonkulus** [comment]
Ok please test this out locally. I will merge and release tomorrow. Thanks!

**Comment by maheshbansod** [comment]
@redonkulus tested the code on my side in a Vite plugin. working well.

**Pull request merged**
