### PR TITLE
refactor(dev): remove grunt usage

### PR DESCRIPTION
**Pull request by redonkulus**
I confirm that this contribution is made under a BSD license and that I have the authority necessary to make this contribution on behalf of its copyright owner.

---

Removing grunt to simplify development. Using postcss to handle import flattening and minification.

### CODE REVIEW

**Comment by carriemorrison** [comment]
Nice to see grunt removed, we should update the readme https://github.com/acss-io/atomizer/blob/master/README.md#plugins

**Comment by carriemorrison** [comment]
Would this break existing usage? e.g. on our repos we have a `gruntfile` config to merge atomizer....

```

    grunt.registerTask('dev', [
        ...
        'atomizer-merge-configs',
        'applet-css:prod',
        'copy',
        'concurrent:app',
    ]);
    grunt.registerTask('build', [
        ...
        'atomizer-merge-configs',
```

**Comment by redonkulus** [comment]
`grunt-atomizer` is still used, this just updates the usage for the docs site.

**Review by carriemorrison — APPROVED** [review]
LGTM

**Pull request merged**
