### PR TITLE
Removing `--ie` option

### PR DESCRIPTION
**Pull request by fidian**
This is a suggestion for what it would take to remove `--ie` as an option, so IE < 8 hacks won't be employed.

### CODE REVIEW

**Comment by thierryk** [comment]
This PR should also consider removing/editing references to "oldIE" and its fixes within https://acss.io/guides/helper-classes.html and https://acss.io/tutorials/grid-system.html.

**Comment by fidian** [comment]
That's a separate repository and out of scope for this pull request. I can find no references to "oldIE" in this codebase.

**Comment by thierryk** [comment]
Right, I meant we can't do this without removing all "oldIE" related stuff from [acss.io](https://acss.io) first.

Also, instead of *removing*:

```
--ie                                adds old IE hacks to the output.
```

I'd replace it with:

```
--ie                                deprecated.
```

**Comment by redonkulus** [comment]
I think it would just be another PR that removes the references. The amount of people relying on this old parameter is probably very small, I don't think we should keep it in the code base to say its deprecated. Furthermore, we would probably need to bump the major version of the package to avoid breaking any people that may actually be relying on this parameter still.

**Comment by redonkulus** [comment]
We are not going to merge this yet until we decide to officially remove IE support. The amount of code is small and will not be outputted unless the `--ie` option is added.

**Comment by redonkulus** [comment]
FYI --ie support was removed in atomizer@3.16.0

**Pull request closed without merging**
