### PR TITLE
Add placeholder pseudo element

### PR DESCRIPTION
**Pull request by soluml**
Add a [placeholder pseudo element](https://developer.mozilla.org/en-US/docs/Web/CSS/::placeholder) to Atomizer.

### CODE REVIEW

**Comment by soluml** [comment]
[Chrome looks to be adding it in 57](https://bugs.chromium.org/p/chromium/issues/detail?id=623345) / Opera in 43. Also looks to be in the TP of Safari ([caniuse](http://caniuse.com/#feat=css-placeholder)).  It's at Working Draft in the [spec](https://drafts.csswg.org/css-pseudo-4/#placeholder-pseudo) and Autoprefixer does a great job of handling the prefixed variants.

**Comment by soluml** [comment]
Everything good @redonkulus?

**Comment by redonkulus** [comment]
@soluml I will wait for @src-code to check this before merging. He is on vacation but will be back next week.

**Comment by src-code** [comment]
Sounds good.  We considered this one back during #236 but didn't end up adding it, I guess due to poor browser support.  With Safari and Chrome adopting it soon, it seems like a good time to support it.

**Pull request merged**
